{
 "title": "Windows Hosts",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Zabbix Data Source",
    "query": "alexanderzobnin-zabbix-datasource"
   },
   { "name": "group", "label": "group", "query": "*" },
   { "name": "host", "query": "$group.*" },
   {
    "name": "network",
    "query": "$group.$host.Network interfaces.*"
   },
   { "name": "Disk", "query": "$group.$host.Filesystems.*" }
  ]
 },
 "panels": [
  {
   "title": "Host Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HostName",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "Host name of zabbix_agentd running"
       },
       "mode": 2,
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "System uptime" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Zabbix Triggers",
     "type": "alexanderzobnin-zabbix-triggers-panel",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "targets": {
      "0": {
       "application": { "filter": "" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "proxy": { "filter": "" },
       "refId": "A",
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      "$datasource": {
       "application": { "filter": "" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "proxy": { "filter": "" },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     }
    },
    {
     "title": "SystemInfo",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "System information" },
       "mode": 2,
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "SystemLoad",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "CPU" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/Processor Util/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "application": { "filter": "Memory" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": { "filter": "/.*/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "Performance" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Latency/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk Transfers/s IOPS",
   "type": "graph",
   "description": "Disk Transfers/sec 指在此盘上读取/写入操作速率。也就是IOPS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/IOPS/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk Tranfer Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/bytes per second/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/queue/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Space on $Disk",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
     "repeat": "Disk",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Filesystems" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/Free disk space on $Disk \\(percentage\\)/"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Free Space on $Disk",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Filesystems" },
       "group": { "filter": "$group" },
       "host": { "filter": "$host" },
       "item": {
        "filter": "/Free disk space on $Disk \\(percentage\\)/"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Net Traf $network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "repeat": "network",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/$network$/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Net Traf $network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/$network$/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Net Traf $network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/$network$/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Net Traf $network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/$network$/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Net Traf $network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/$network$/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}